[package]
name = "learn-rust"
version = "0.0.1"
edition = "2021"

[workspace]
members = [
    "module1",
    "module2",
    "module3",
    "module4",
    "minigrep",
    "inheritance",
    #"patterns",
]
